#!/usr/bin/env bash

# don't output the result or errors
# of this command
echo "Running intial build..."
dotnet build > /dev/null 2>&1

set -x
dotnet msbuild /p:Configuration=Release ZulipCSharp.sln

# allow previous build to fail
set -e
dotnet restore ZulipCSharp.sln
cd TestServer
npm i

# make sure xunit is binded to dotnet
cd ../Tests
dotnet restore
